version: '3'
services:
  db_dev:
    image: "postgres:14.2"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT_DEV}:5432"
  db_test:
    image: "postgres:14.2"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT_TEST}:5432"
